/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/opVkXQ3p29gSlIBz/scene.splinecode"
  );
  return (
    <>
      <group {...props} dispose={null}>
        <OrthographicCamera
          name="Default Camera"
          makeDefault={true}
          zoom={0.8}
          far={50000}
          near={-50000}
          position={[1.7, 0, 998.56]}
          rotation={[0, 0, 0]}
          scale={1}
        >
          <directionalLight
            name="Default Directional Light"
            intensity={0.99}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            color="#dadada"
            position={[850000, 1300000, 1000000]}
          />
        </OrthographicCamera>
        <group name="rocket" rotation={[0, 0, 0.45]}>
          <mesh
            name="Up"
            geometry={nodes.Up.geometry}
            material={nodes.Up.material}
            castShadow
            receiveShadow
            position={[8.5, 36.8, 34.89]}
            rotation={[0, 0, 0.03]}
            scale={[0.76, 0.77, 0.77]}
          />
          <group
            name="Window_Up"
            position={[5.83, 102.47, 130.28]}
            rotation={[0.07, 0, 0.03]}
            scale={0.89}
          >
            <mesh
              name="Cylinder 2"
              geometry={nodes["Cylinder 2"].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[0, 3.42, 8.15]}
              rotation={[1.27, 0, 0]}
              scale={[0.79, 0.38, 0.79]}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[0, 0, -3.02]}
              rotation={[1.27, 0, 0]}
              scale={[1, 0.47, 1]}
            />
          </group>
          <group
            name="Empty Object"
            position={[9.25, 4.35, 140.14]}
            rotation={[-0.09, 0, 0.03]}
            scale={0.77}
          >
            <group
              name="Window_Down"
              position={[0, 0, 0]}
              rotation={[0.42, 0, 0]}
              scale={1.17}
            >
              <mesh
                name="Cylinder 21"
                geometry={nodes["Cylinder 21"].geometry}
                material={materials.Untitled}
                castShadow
                receiveShadow
                position={[0, 3.42, 8.15]}
                rotation={[1.27, 0, 0]}
                scale={[0.79, 0.38, 0.79]}
              />
              <mesh
                name="Cylinder1"
                geometry={nodes.Cylinder1.geometry}
                material={materials.Untitled}
                castShadow
                receiveShadow
                position={[0, 0, -3.02]}
                rotation={[1.27, 0, 0]}
                scale={[1, 0.47, 1]}
              />
            </group>
          </group>
          <mesh
            name="Body White"
            geometry={nodes["Body White"].geometry}
            material={nodes["Body White"].material}
            castShadow
            receiveShadow
            position={[8.56, 35.23, 35.45]}
            rotation={[0, 0, 0.03]}
            scale={0.8}
          />
          <group
            name="Blue part_1"
            position={[102.4, -20.29, 91.83]}
            rotation={[0, 0, 0.03]}
            scale={0.77}
          >
            <mesh
              name="Shape 2"
              geometry={nodes["Shape 2"].geometry}
              material={materials[""]}
              castShadow
              receiveShadow
              position={[-16.57, 16.59, -22.43]}
              rotation={[0.03, -0.47, -0.73]}
              scale={[0.5, 0.47, 0.41]}
            />
            <mesh
              name="Shape"
              geometry={nodes.Shape.geometry}
              material={materials[""]}
              castShadow
              receiveShadow
              position={[-6.55, 13.71, -12.03]}
              rotation={[0.03, -0.47, -0.73]}
              scale={[0.45, 0.42, 0.37]}
            />
          </group>
          <group
            name="Blue part_2"
            position={[38.98, -22.51, -71.17]}
            rotation={[-2.99, 1.34, 2.99]}
            scale={0.77}
          >
            <mesh
              name="Shape 21"
              geometry={nodes["Shape 21"].geometry}
              material={materials[""]}
              castShadow
              receiveShadow
              position={[-16.57, 16.59, -22.43]}
              rotation={[0.03, -0.47, -0.73]}
              scale={[0.5, 0.47, 0.41]}
            />
            <mesh
              name="Shape1"
              geometry={nodes.Shape1.geometry}
              material={materials[""]}
              castShadow
              receiveShadow
              position={[-6.55, 13.71, -12.03]}
              rotation={[0.03, -0.47, -0.73]}
              scale={[0.45, 0.42, 0.37]}
            />
          </group>
          <group
            name="Blue part_3"
            position={[-93.75, -27.14, 66.2]}
            rotation={[-3.13, -0.75, 3.13]}
            scale={0.77}
          >
            <mesh
              name="Shape 22"
              geometry={nodes["Shape 22"].geometry}
              material={materials[""]}
              castShadow
              receiveShadow
              position={[-16.57, 16.59, -22.43]}
              rotation={[0.03, -0.47, -0.73]}
              scale={[0.5, 0.47, 0.41]}
            />
            <mesh
              name="Shape2"
              geometry={nodes.Shape2.geometry}
              material={materials[""]}
              castShadow
              receiveShadow
              position={[-6.55, 13.71, -12.03]}
              rotation={[0.03, -0.47, -0.73]}
              scale={[0.45, 0.42, 0.37]}
            />
          </group>
          <mesh
            name="bottom"
            geometry={nodes.bottom.geometry}
            material={nodes.bottom.material}
            castShadow
            receiveShadow
            position={[12.01, -75.76, 36.76]}
            rotation={[0, 0, 0.03]}
            scale={0.79}
          />
          <mesh
            name="Engine"
            geometry={nodes.Engine.geometry}
            material={materials.Untitled}
            castShadow
            receiveShadow
            position={[11.6, -89.22, 36.77]}
            rotation={[Math.PI / 2, 0.03, 0]}
            scale={[0.85, 0.85, 1.67]}
          />
          <mesh
            name="Fire_Red"
            geometry={nodes.Fire_Red.geometry}
            material={nodes.Fire_Red.material}
            castShadow
            receiveShadow
            position={[14.51, -156.4, 36.27]}
            rotation={[0, 0, 0.03]}
            scale={[0.67, 0.86, 0.67]}
          />
        </group>
        <hemisphereLight name="Default Ambient Light" intensity={0.75} />
      </group>
    </>
  );
}
